### ISSUE TITLE
bug: edited link-list title doesn't get saved if user already created a link but then added more list entries

### ISSUE THREAD

**Issue by D4n2021** [denno020/linkslist#10]
- add links
- click "create link"
- add more links
- edit link-list title
now open linklist in new browser tab/window, title still says "Links List".

**Comment by denno020** [comment]
Hey @Dani3lNL, thank you for the bug report!

I've just tried to replicate, but for me, the title changed as expected.

Did you hit the Enter/Return key after changing the title of the list? That will trigger the app to actually save the change.

Something I need to figure out how to make a bit clearer

**Comment by D4n2021** [comment]
aaaah that caused, it, thank you. Might be good to add that info on that page, because many users will expect it to work the way I did, by clicking out of the field into the white backgroud, with left mousebutton.
Idea: make a small info-box open up stating "hit enter to save" as soon as the cursor blinks in that field. 👍

**Comment by denno020** [comment]
I think I'll just implement left-click-to-save. Might be easier than trying to fit pop up messages into the UI nicely :).

Thanks again for bringing this to my attention

**Comment by D4n2021** [comment]
And thanks for reacting so fast! :)

**Comment by denno020** [comment]
Update has been made and released in 1.6.0
