### ISSUE TITLE
Collab vs Private

### ISSUE THREAD

**Issue by yada-yoda** [denno020/linkslist#11]
Any chance to have a feature so that your list is only editable by you? Sometimes we need to give someone a list for a few people without that other person editing that list; and messing it up for someone else.

**Comment by denno020** [comment]
Hey @yada-yoda, thanks for the feature request!

I'm actually working on that right now. I was hoping to have it released by the start of this year, however have hit a few snags with the way data is managed.

Rest assured, this is my highest priority right now

**Comment by denno020** [comment]
Hey @yada-yoda, just wanted to let you know that the ability to create a locked list has been released in version 1.7.0 of Links List!
