### ISSUE TITLE
feature request: a button to link to linkslist.app starting page.

### ISSUE THREAD

**Issue by D4n2021** [denno020/linkslist#12]
So that on a custom link list, a user can easily open a new tab with the https://www.linkslist.app starting page, to create a new linklist.

**Comment by denno020** [comment]
Hi @Dani3lNL, that's a great suggestion!

I will add it to the To Do list

**Comment by denno020** [comment]
Hey @Dani3lNL, just wanted to let you know that Links List 1.7.0 now has a New List button, making it much easier to start a fresh list :)
