### ISSUE TITLE
404

### ISSUE THREAD

**Issue by electric-m** [denno020/linkslist#13]
Unable to preview link
Request failed with status code 404

Appears when adding iOS AppStore links.

**Comment by denno020** [comment]
Hey @FM-500,

Thanks for reaching out! Unfortunately, some websites don't appear to be set up with the required meta data that Links List looks for. Links List looks for meta data that all websites/web pages probably _should_ have, but some websites choose not to implement this data for whatever reason.

I've got a feature on my to do list being the ability to edit the name/description of a link that is added to a list.
This will allow us to work around the issue with data missing on the other end of the link.

If you'd like to follow along with progress an release of new features, please sub to the newsletter on the website :)

**Comment by electric-m** [comment]
Excuse me, but where would I subscribe to news?
You mean following on GitHub?

Michael Freyler
07644 9234478 | michael@freyler.eu
Wagenstadter Weg 5 | 79341 Kenzingen
Am 20. Jan. 2021, 20:34 +0100 schrieb Luke <notifications@github.com>:

**Comment by denno020** [comment]
Hey Michael!

On the landing homepage of Links List, near the bottom, there is a newsletter sign up. Just enter your email there and you'll receive updates.

Thanks!
