### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by slaction** [denno020/linkslist#15]
Could you add a function that shows the current number of links in a list?

I'd like to be able to see the number of links I have at a glance.

Love the app, thanks.

**Comment by denno020** [comment]
Hey Slaction,

Great suggestion! I will definitely add that to the To Do list, and see where we can fit in into the UI.

Thanks!

**Comment by slaction** [comment]
Awesome!  Thanks for the quick response!

**Comment by denno020** [comment]
Hey @slaction, just wanted to let you know that Links List 1.7.0 now includes a count of the number of items in a list :)
