### ISSUE TITLE
Unable to preview link Error: Request failed with status code 403

### ISSUE THREAD

**Issue by rejaeika** [denno020/linkslist#22]
I keep getting this error with certain websites like Amazon, Ubran outfitters

**Comment by denno020** [comment]
Hey @rejaeika, thanks for reaching out!

Unfortunately some websites don't scrape very nicely, either they don't have meta data available (which is what Links List attempts to read), or it blocks LinksList from reading any data at all.
Unfortunately I can't really do much about this, however I am working on a work around which will at least let people edit the title/description to something they know represents the link. The link will still function normally, it just doesn't look at pretty in the list.
